import terser from '@rollup/plugin-terser';

import { defineConfig } from 'vite';
import { resolve } from 'path';
import { name, version } from './package.json';

export default defineConfig({
  define: {
    __VERSION__: `"${version}"`,
  },
  test: {
    coverage: {
      provider: 'c8' // or 'c8'
    },
  },
  esbuild: {
    include: ['json'],
  },
  build: {
    minify: 'terser',
    rollupOptions: {
      output: {
        banner: () => [
          '/*!',
          ' * This file is an extension for the Lavendeux parser',
          ' * https://rscarson.github.io/lavendeux/',
          ' * ',
          ' * The contents below were autogenerated using the lavendeux npm package:',
          ' * https://www.npmjs.com/package/lavendeux',
          ' */',
        ].join('\n')
      },
      plugins: [terser()]
    },
    lib: {
      entry: resolve(__dirname, 'src/runners/index.js'),
      formats: ['es'],
      name: name,
      fileName() {
        return `${name}.js`;
      },
    },
  },
});